In [229]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [230]:
df=pd.read_csv("skills2025.csv")
print(df.shape)

(65437, 114)

In [231]:
cols=["DevType", "Industry", "LanguageHaveWorkedWith", "LanguageWantToWorkWith", "LanguageAdmired", "DatabaseHaveWorkedWith", "DatabaseWantToWorkWith", "DatabaseAdmired", "PlatformHaveWorkedWith", "PlatformWantToWorkWith", "PlatformAdmired", "WebframeHaveWorkedWith", "WebframeWantToWorkWith", "WebframeAdmired", "EmbeddedHaveWorkedWith", "EmbeddedWantToWorkWith", "EmbeddedAdmired", "MiscTechHaveWorkedWith", "MiscTechWantToWorkWith", "MiscTechAdmired", "ToolsTechHaveWorkedWith", "ToolsTechWantToWorkWith", "ToolsTechAdmired", "NEWCollabToolsHaveWorkedWith", "NEWCollabToolsWantToWorkWith", "NEWCollabToolsAdmired", "OfficeStackAsyncHaveWorkedWith", "OfficeStackAsyncWantToWorkWith", "OfficeStackAsyncAdmired", "OfficeStackSyncHaveWorkedWith", "OfficeStackSyncWantToWorkWith", "OfficeStackSyncAdmired","YearsCode", "YearsCodePro", "WorkExp"]
df=df[cols]

In [232]:
df.dropna(subset=['DevType'],inplace=True)
df['DevType'].isnull().sum()

np.int64(0)

In [233]:
null_list_temp=df.isnull().sum()
null_list_temp=pd.DataFrame(null_list_temp)
null_list_temp.reset_index(inplace=True)
null_list_temp.rename(columns={'index':'field',0:'null_entries'},inplace=True)
null_list_temp.sort_values(by=['null_entries'],inplace=True,ascending=False)
null_list_temp

                             field  null_entries
16                 EmbeddedAdmired         43173
15          EmbeddedWantToWorkWith         42338
14          EmbeddedHaveWorkedWith         37914
1                         Industry         30619
19                 MiscTechAdmired         30562
34                         WorkExp         29841
10                 PlatformAdmired         28937
18          MiscTechWantToWorkWith         27276
9           PlatformWantToWorkWith         25910
13                 WebframeAdmired         25454
28         OfficeStackAsyncAdmired         22769
7                  DatabaseAdmired         22017
12          WebframeWantToWorkWith         21999
17          MiscTechHaveWorkedWith         21044
27  OfficeStackAsyncWantToWorkWith         21038
8           PlatformHaveWorkedWith         18381
6           DatabaseWantToWorkWith         18212
22                ToolsTechAdmired         16387
11          WebframeHaveWorkedWith         15674
31          OfficeStackSyncAdmired         15437
21         ToolsTechWantToWorkWith         14368
30   OfficeStackSyncWantToWorkWith         13480
26  OfficeStackAsyncHaveWorkedWith         12136
5           DatabaseHaveWorkedWith         10903
4                  LanguageAdmired         10340
25           NEWCollabToolsAdmired          9818
24    NEWCollabToolsWantToWorkWith          8488
20         ToolsTechHaveWorkedWith          8204
33                    YearsCodePro          8152
3           LanguageWantToWorkWith          5758
29   OfficeStackSyncHaveWorkedWith          4849
23    NEWCollabToolsHaveWorkedWith          3179
2           LanguageHaveWorkedWith          2050
32                       YearsCode           257
0                          DevType             0

In [234]:
#add core fields that are absolutely necessary for dataset
df=df[["DevType", "LanguageHaveWorkedWith", "LanguageWantToWorkWith", "DatabaseHaveWorkedWith", "DatabaseWantToWorkWith", "YearsCode", "YearsCodePro"]]

In [235]:
#check if no of null entries are still within threshold currently 10% null rate
(df.isnull().sum().sum()/(df.shape[0]*df.shape[1])*100).round(2)

np.float64(10.89)

In [236]:
#Dropping responses by students and renaming 'others pls specify' to 'others' in DevType
df.loc[df['DevType']=='Other (please specify):',['DevType']]='Others'
df=df[(df['DevType']!='Student') & (df['DevType']!='Others')]

In [237]:
"YearsCode and YearsCodePro both have certain string values namely less than 1 year , more than 50 years we wincisor them to 0 and 51,respectively"
df.loc[df['YearsCode']=='Less than 1 year',['YearsCode']]='0'
df.loc[df['YearsCode']=='More than 50 years',['YearsCode']]='51'
df.loc[df['YearsCodePro']=='Less than 1 year',['YearsCodePro']]='0'
df.loc[df['YearsCodePro']=='More than 50 years',['YearsCodePro']]='51'

In [ ]:
#handling null values in the dataset
df.isnull().sum()
df

DevType                       0
LanguageHaveWorkedWith     1705
LanguageWantToWorkWith     5006
DatabaseHaveWorkedWith     8373
DatabaseWantToWorkWith    14735
YearsCode                   199
YearsCodePro               3684
dtype: int64

In [239]:
"""
#converting YearsCode & YearsCodePro to int
df=df.astype({'YearsCode':int,'YearsCodePro':int})
"""

"\n#converting YearsCode & YearsCodePro to int\ndf=df.astype({'YearsCode':int,'YearsCodePro':int})\n"

In [240]:
ls=df["YearsCodePro"].value_counts().index
print(ls)

Index(['3', '2', '5', '10', '4', '6', '8', '7', '1', '0', '12', '15', '20',
       '9', '11', '13', '14', '25', '16', '18', '17', '30', '24', '19', '22',
       '23', '26', '27', '21', '28', '35', '32', '29', '40', '34', '33', '38',
       '36', '31', '37', '45', '39', '41', '42', '51', '44', '43', '46', '48',
       '50', '49', '47'],
      dtype='str', name='YearsCodePro')

In [241]:
df["YearsCodePro"].value_counts(normalize=True)

YearsCodePro
3     0.080040
2     0.079915
5     0.069874
10    0.064833
4     0.063235
6     0.056845
8     0.051555
7     0.050352
1     0.047634
0     0.039999
12    0.035622
15    0.032489
20    0.030601
9     0.029916
11    0.026369
13    0.022634
14    0.021742
25    0.019605
16    0.018900
18    0.017178
17    0.016037
30    0.013423
24    0.012469
19    0.010249
22    0.009792
23    0.009066
26    0.008485
27    0.007572
21    0.007406
28    0.006597
35    0.005643
32    0.003900
29    0.003838
40    0.003817
34    0.003299
33    0.002552
38    0.002510
36    0.002344
31    0.002012
37    0.001950
45    0.001079
39    0.001037
41    0.000975
42    0.000954
51    0.000830
44    0.000788
43    0.000685
46    0.000394
48    0.000290
50    0.000228
49    0.000228
47    0.000207
Name: proportion, dtype: float64

In [242]:
df

,DevType,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,YearsCode,YearsCodePro
1,"Developer, full-stack",Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,20,17
2,Developer Experience,C#,C#,Firebase Realtime Database,Firebase Realtime Database,37,27
3,"Developer, full-stack",C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,4,NaN
4,"Developer, full-stack",C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,9,NaN
6,Academic researcher,R,R,NaN,NaN,7,7
...,...,...,...,...,...,...,...
65428,"Developer, back-end",NaN,NaN,NaN,NaN,4,7
65431,"Developer, full-stack",Bash/Shell (all shells);C;C#;C++;Delphi;Groovy...,Bash/Shell (all shells);C#;Go;HTML/CSS;Java;Ja...,Couch DB;H2;Microsoft SQL Server;MySQL;Oracle;...,Elasticsearch;PostgreSQL;Redis,38,24
65432,Blockchain,NaN,NaN,NaN,NaN,5,3
65434,"Developer, mobile",NaN,NaN,NaN,NaN,9,5
65435,"Developer, back-end",C;C++;Go;Lua;Objective-C;Python;Rust;SQL,Rust;SQL,PostgreSQL;SQLite,PostgreSQL;SQLite,5,2

In [243]:
df.to_csv('current dataset.csv')